# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_auto_20161121_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strip',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
