# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_auto_20161121_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='strip',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
