# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_auto_20170111_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
    ]
